### PR TITLE
fix listing menu items

### PR DESCRIPTION
**Pull request by barisdongel**
Listing menu items with position

### CODE REVIEW

**Comment by cploutarchou** [comment]
@barisdongel can you update your code from master and place your change on the helper file. Then create a new merge request. Thanks a lot

**Comment by barisdongel** [comment]
> @barisdongel can you update your code from master and place your change on the helper file. Then create a new merge request. Thanks a lot

Of course but your project is gone. Can u check it and fix. After that i can create a new merge request.

**Comment by cploutarchou** [comment]
What do you mean? Is gone. Maybe the branch u create you mean?

**Comment by barisdongel** [comment]
I mean the project on your reposity has changed. This is another JavaScript project.

**Comment by cploutarchou** [comment]
Oh let me  check it I sync reps with GitLab today and may I make something wrong. Thanks for letting me know.

**Comment by barisdongel** [comment]
You're welcome sir. Have a nice work.

**Comment by barisdongel** [comment]
Hey sir. Your project still need back to old version.

**Comment by cploutarchou** [comment]
Dear @barisdongel  repo has been updated with the correct code. Can you please apply the corrections and make a new pull request

**Comment by barisdongel** [comment]
Yeah its nice. I will make pull request

**Pull request closed without merging**
